### ISSUE TITLE
Mac Mini

### ISSUE THREAD

**Issue by itjustcrashed** [AppleWOA/apple_silicon_platforms_mu#2]
I see no mac mini platform in the `Platforms` directory...

**Comment by amarioguy** [comment]
Hello!

Right now the highest priority item is getting Mac Studio support working, so I haven't been able to prioritize having Mac mini support added. I should be able to do that soon though, I'd just need to make the configuration files to build it, which I can get done ASAP ultimately, as a lot of this is shared with the M1 MacBook Air (which I have partial support for)

Adding this to my near term todo list, closing
