### ISSUE TITLE
How to use this UEFI firmware properly?

### ISSUE THREAD

**Issue by Android-Piepaint** [AppleWOA/apple_silicon_platforms_mu#3]
I'm interested in this project, and I am using Asahi Linux on my MacBook Air(2020) with M1 chip. How to compile this UEFI firmware properly? Should I use the [m1n1 Windows](https://github.com/AppleWOA/m1n1_windows) repository? If I need, how to use it? Give me a simple guide, please.

**Comment by The-Synthax** [comment]
There aren't yet instructions available, as there's not much point in publishing them. It cannot run Windows in its current state.

**Comment by amarioguy** [comment]
Right now, the firmware's not really buildable outside of debug and my specific machine, I need to spin up a CI configuration to run builds for release configuration, I also just generally need to update a lot of the configuration stuff, which is on hold until a demo of windows booting is done.

A guide will be out soon once this is beyond "barely alpha" stage
