### ISSUE TITLE
Discord Server

### ISSUE THREAD

**Issue by Retr0Aa** [AppleWOA/apple_silicon_platforms_mu#4]
Hello, I want to join the discord server of this project, but the link in the description is invalid, so can you please give me working link?

Thanks in advance.

**Comment by pivotman319-owo** [comment]
> Hello, I want to join the discord server of this project, but the link in the description is invalid, so can you please give me working link?
> 
> Thanks in advance.

feel free to join [here](https://discord.gg/tXEkacZdZ5).

**Comment by Retr0Aa** [comment]
Thanks for the link!
